spring.application.name=fit-balance
#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost/fitbalance
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.ai.openai.base-url=https://api.proxyapi.ru/openai
spring.ai.openai.api-key=sk-qAFtMNoQtFZyoyMk0g1WgoFyr4x2Mhi6
