spring.application.name=fit-balance

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
