spring.application.name=fit-balance
#Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost/fitbalance
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
