server.port=9090
#server.servlet.context-path=/stats

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL2:jdbc:postgresql://localhost/stats}
spring.datasource.username=${SPRING_DATASOURCE_USER2:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD2:root}
spring.datasource.driverClassName=${SPRING_DRIVER_CLASS_NAME2:org.postgresql.Driver}

spring.liquibase.change-log=classpath:/db2/changelog/db2.changelog-master.xml
#JPA configuration
spring.jpa.open-in-view=false
spring.thymeleaf.encoding=UTF-8

app-service.url=${APP_SERVICE_URL:http://localhost:8090}
